package org.example.controller;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import org.example.MainApp;
import org.example.service.InviteService;
import org.example.service.UserService;
import org.example.util.SessionManager;

import java.util.List;

public class AlertsController {

    @FXML
    private Button backButton;

    @FXML
    private ListView<String> parentInvitesList;

    @FXML
    private ListView<String> groupInvitesList;

    @FXML
    private ListView<String> financialAlertsList;

    @FXML
    private Button acceptParentInviteButton;

    @FXML
    private Button declineParentInviteButton;

    @FXML
    private Button acceptGroupInviteButton;

    @FXML
    private Button declineGroupInviteButton;

    @FXML
    private Button dismissAlertButton;

    private final ObservableList<String> parentInvites = FXCollections.observableArrayList();
    private final ObservableList<String> groupInvites = FXCollections.observableArrayList();
    private final ObservableList<String> financialAlerts = FXCollections.observableArrayList();

    private final java.util.Map<String, String> parentInviteMap = new java.util.HashMap<>();
    private final java.util.Map<String, String> groupInviteMap = new java.util.HashMap<>();

    @FXML
    public void initialize() {
        // Back should go to Mode Selection
        backButton.setOnAction(e -> loadModeSelection());
        loadInvitesAndAlerts();
        setupSelectionHandlers();
    }

    private void loadModeSelection() {
        try {
            javafx.fxml.FXMLLoader loader = new javafx.fxml.FXMLLoader(
                getClass().getResource("/fxml/mode_selection.fxml"));
            javafx.scene.Parent root = loader.load();
            javafx.scene.Scene scene = new javafx.scene.Scene(root);
            scene.getStylesheets().add(getClass().getResource("/css/styles.css").toExternalForm());
            MainApp.getPrimaryStage().setScene(scene);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void loadInvitesAndAlerts() {
        var currentUser = SessionManager.getInstance().getCurrentUser();
        if (currentUser == null) {
            MainApp.loadLogin();
            return;
        }
        // Parent invites (for child to accept)
        List<String[]> pInv = InviteService.getPendingParentInvitesForChild(currentUser.getUserId());
        parentInvites.clear();
        parentInviteMap.clear();
        for (String[] row : pInv) {
            String inviteId = row[0];
            String parentId = row[1];
            var parentUser = UserService.getUserById(parentId);
            String display = "Parent: " + (parentUser != null ? parentUser.getName() : parentId) + " wants to add you";
            parentInvites.add(display);
            parentInviteMap.put(display, inviteId);
        }
        parentInvitesList.setItems(parentInvites);

        // Group invites
        List<String[]> gInv = InviteService.getPendingGroupInvitesForUser(currentUser.getUserId());
        groupInvites.clear();
        groupInviteMap.clear();
        for (String[] row : gInv) {
            String inviteId = row[0];
            String groupId = row[1];
            var group = org.example.service.GroupService.getGroupById(groupId);
            String groupName = group != null ? group.getGroupName() : groupId;
            String display = "Group invite: " + groupName;
            groupInvites.add(display);
            groupInviteMap.put(display, inviteId);
        }
        groupInvitesList.setItems(groupInvites);

        // Financial alerts - placeholder list for now (later generated by AlertEngine)
        financialAlerts.clear();
        // Example placeholder alert; you can remove when AlertEngine generates real ones
        // financialAlerts.add("Monthly budget nearing limit");
        financialAlertsList.setItems(financialAlerts);

        acceptParentInviteButton.setDisable(true);
        declineParentInviteButton.setDisable(true);
        acceptGroupInviteButton.setDisable(true);
        declineGroupInviteButton.setDisable(true);
        dismissAlertButton.setDisable(true);
    }

    private void setupSelectionHandlers() {
        parentInvitesList.getSelectionModel().selectedItemProperty().addListener((obs, o, n) -> {
            boolean selected = n != null;
            acceptParentInviteButton.setDisable(!selected);
            declineParentInviteButton.setDisable(!selected);
        });
        groupInvitesList.getSelectionModel().selectedItemProperty().addListener((obs, o, n) -> {
            boolean selected = n != null;
            acceptGroupInviteButton.setDisable(!selected);
            declineGroupInviteButton.setDisable(!selected);
        });
        financialAlertsList.getSelectionModel().selectedItemProperty().addListener((obs, o, n) -> {
            boolean selected = n != null;
            dismissAlertButton.setDisable(!selected);
        });

        acceptParentInviteButton.setOnAction(e -> {
            String key = parentInvitesList.getSelectionModel().getSelectedItem();
            if (key == null) return;
            String inviteId = parentInviteMap.get(key);
            if (InviteService.acceptParentInvite(inviteId)) {
                loadInvitesAndAlerts();
            }
        });
        declineParentInviteButton.setOnAction(e -> {
            String key = parentInvitesList.getSelectionModel().getSelectedItem();
            if (key == null) return;
            String inviteId = parentInviteMap.get(key);
            if (InviteService.declineParentInvite(inviteId)) {
                loadInvitesAndAlerts();
            }
        });
        acceptGroupInviteButton.setOnAction(e -> {
            String key = groupInvitesList.getSelectionModel().getSelectedItem();
            if (key == null) return;
            String inviteId = groupInviteMap.get(key);
            if (InviteService.acceptGroupInvite(inviteId)) {
                loadInvitesAndAlerts();
            }
        });
        declineGroupInviteButton.setOnAction(e -> {
            String key = groupInvitesList.getSelectionModel().getSelectedItem();
            if (key == null) return;
            String inviteId = groupInviteMap.get(key);
            if (InviteService.declineGroupInvite(inviteId)) {
                loadInvitesAndAlerts();
            }
        });
        dismissAlertButton.setOnAction(e -> {
            // For now just remove the selected alert locally
            String key = financialAlertsList.getSelectionModel().getSelectedItem();
            if (key == null) return;
            financialAlerts.remove(key);
            financialAlertsList.setItems(financialAlerts);
            dismissAlertButton.setDisable(true);
        });
    }
}
